#!/usr/bin/env python3
# wiki-build 2단계: 신규 raw 75개의 소스 요약 생성 → wiki/sources/ (raw/ 구조 미러)
# source_hash는 git hash-object로 직접 계산. 요약/개념은 빌드 시점 판단(사후 관계 명시 허용).
import os, subprocess

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

# (raw 상대경로, 추가태그, 요약, [개념들])
ENTRIES = [
    # ---------- slack (35) ----------
    ("raw/slack/2026-03-05-pg-interface-naming.md", "slack",
     "PG 인터페이스 명명 논의 — PaymentGateway로 확정(PgClient는 postgres와 혼동), 메서드는 approve/cancel/getStatus 3개로 시작. 토스 어댑터 우선.",
     ["PG 추상화"]),
    ("raw/slack/2026-03-09-idempotency-research.md", "slack",
     "멱등성 조사 중간공유 — Stripe 방식(클라 생성 Idempotency-Key + 서버 응답 캐시)이 유력. 서버 생성 방식은 정당한 재결제 구분 불가로 배제 분위기. 3/11 결정의 사전 논의.",
     ["멱등성"]),
    ("raw/slack/2026-03-12-sdk-key-enforcement.md", "slack",
     "3/11 결정 후속 — SDK 미사용 직접호출 가맹점 2곳에 2주 유예 공지 후 키 없는 요청 400 거부 확정.",
     ["멱등성"]),
    ("raw/slack/2026-03-13-redis-ttl-question.md", "slack",
     "멱등키 TTL 24h 만료 후 같은 키 재시도가 신규 결제로 처리되는 엣지 케이스 제기(준호) — '확률 낮으니 일단 24h' 보류로 종결. (6/10에 실측 7건으로 재부상하는 미결 사안.)",
     ["멱등성"]),
    ("raw/slack/2026-03-17-webhook-merchant-500.md", "slack",
     "가맹점 A 서버 500으로 웹훅 유실 — 재시도 정책 부재가 드러나 3/18 웹훅 재시도 결정의 직접 계기가 된 스레드. 재시도 시 중복 수신 문제도 함께 제기됨.",
     ["웹훅 전송"]),
    ("raw/slack/2026-03-20-deploy-rollback-scare.md", "slack",
     "토스 어댑터 v0.2 배포 중 헬스체크 경로 누락으로 롤백 1회. 배포 체크리스트에 헬스체크 항목 추가.",
     ["PG 추상화"]),
    ("raw/slack/2026-03-24-settlement-dplus1-pm.md", "slack",
     "3/25 정산 회의 사전 확인 — 가맹점·영업 모두 D+1 충분(경쟁사 동일), 명세서 정확성이 더 중요. 환불-정산 경계 논의 예고.",
     ["정산 배치"]),
    ("raw/slack/2026-03-27-settlement-key-naming.md", "slack",
     "**슬랙에서만 내려진 결정** — 정산 멱등키는 별도 키 컬럼 없이 (merchant_id, settlement_date) 복합 유니크로. 정식 결정문서 없이 이 스레드가 유일한 근거.",
     ["정산 배치", "멱등성"]),
    ("raw/slack/2026-03-31-team-dinner.md", "slack",
     "3월 회식 일정 잡기 — 업무 무관 잡담.",
     []),
    ("raw/slack/2026-04-02-for-update-deadlock.md", "slack",
     "SELECT FOR UPDATE 데드락 — 락 획득 순서를 payment→ledger로 통일해 해결. DB 선택 회의(4/8) 직전의 postgres 운영 경험.",
     ["PostgreSQL 선택"]),
    ("raw/slack/2026-04-07-mongo-vs-postgres.md", "slack",
     "DB 회의 전날 사전 논쟁 — PM의 'mongo 왜 안 써요?'에 트랜잭션·유니크 제약·스키마 경직성(금액 필드 보호)이 결제에 필수라는 반론. 4/8 회의의 배경.",
     ["PostgreSQL 선택"]),
    ("raw/slack/2026-04-10-numeric-vs-bigint.md", "slack",
     "4/8 NUMERIC 결정에 대한 사후 이견(BIGINT 원 단위 제안) — 수수료 중간계산 소수점·저장/계산 타입 분리 위험을 근거로 NUMERIC 유지, 'KRW는 scale 0 시작'으로 정제. 회의록엔 없는 디테일.",
     ["PostgreSQL 선택", "수수료 계산"]),
    ("raw/slack/2026-04-14-promo-traffic-forecast.md", "slack",
     "4/21 프로모션 트래픽 3배 사전 경고(민지) — API 오토스케일·토스 rate limit만 점검하고 redis는 점검 대상에서 빠짐. 일주일 뒤 INC-204(redis 지연발 중복결제)의 복선.",
     ["비동기 결제 승인", "멱등성"]),
    ("raw/slack/2026-04-21-inc204-realtime.md", "slack",
     "INC-204 실시간 대응 스레드 — redis latency 급등 중 결제가 계속 통과하는 것을 발견, 코드가 fail-open임을 서연이 확인('타임아웃=키 없음=신규'). 도현이 본인 결정임을 즉석 인정, 당일 fail-closed 핫픽스 배포.",
     ["멱등성", "fail-closed 원칙"]),
    ("raw/slack/2026-04-22-inc204-refund-ops.md", "slack",
     "INC-204 수습 — 중복 청구 87건 전액 환불 + 쿠폰 보상 당일 완료, 항의 가맹점 2곳 직접 통화.",
     ["멱등성"]),
    ("raw/slack/2026-04-23-failopen-debate.md", "slack",
     "fail-open/fail-closed 개념 정리 스레드 — fail-open 자체는 도메인 의존(카운터엔 적합)이나, 결제는 '잘못 통과'의 비용이 '잘못 거부'보다 압도적이라 fail-closed가 기본. 포스트모템 결론의 사전 정리.",
     ["fail-closed 원칙", "멱등성"]),
    ("raw/slack/2026-04-28-idem-table-ddl.md", "slack",
     "payment_idempotency 테이블 DDL 초안 — 키를 PK로(유니크 제약 겸용), request_hash로 같은 키·다른 바디(클라 버그)를 409 거부. 4/29 결정 회의의 기술 초안.",
     ["멱등성", "PostgreSQL 선택"]),
    ("raw/slack/2026-05-02-webhook-secret-storage.md", "slack",
     "**슬랙에서만 내려진 결정** — webhook_secret 보관은 vault 대신 DB 암호화 컬럼(pgcrypto), KMS는 다음 분기 검토. 시크릿 회전 API도 함께 지시.",
     ["웹훅 전송", "PostgreSQL 선택"]),
    ("raw/slack/2026-05-07-hmac-encoding-issue.md", "slack",
     "HMAC 간헐 검증 실패 원인 — json 재직렬화로 키 순서가 바뀌어 서명 불일치. '전송 직전 raw bytes로 서명'으로 수정, 가맹점 가이드에 '받은 바디 그대로 검증' 명시.",
     ["웹훅 전송"]),
    ("raw/slack/2026-05-08-merchant-signature-docs.md", "slack",
     "가맹점 B의 서명 검증 샘플 요청 — java 샘플 부재 확인 후 당일 작성. 7/1 필수화 전 언어별 샘플 확충 방침.",
     ["웹훅 전송"]),
    ("raw/slack/2026-05-12-inc231-realtime.md", "slack",
     "INC-231 실시간 스레드 — 04:31 '30분 초과' 알람 후 도현이 배치를 죽음으로 오판해 04:41 수동 재실행('재실행 돌릴게요'), 1차가 살아있어 이중 송금 3곳 1,840만원. 명세서엔 멱등키가 있으나 송금 호출엔 가드 부재가 현장에서 확인됨.",
     ["정산 배치", "멱등성"]),
    ("raw/slack/2026-05-13-inc231-recovery.md", "slack",
     "INC-231 회수 — 이중송금 3곳 통화 후 당일 1,840만원 전액 회수. payout_log 유니크 가드 PR 착수.",
     ["정산 배치"]),
    ("raw/slack/2026-05-14-batch-lock-discussion.md", "slack",
     "배치 락 기술 선택 논쟁 — pg advisory lock(의존성 無, 커넥션 해제 시 자동 풀림) vs redis lock. '락 실패=실행 안 함이라 redis가 죽어도 안전한 실패'라는 fail-closed 논리로 redis lock 채택, TTL 2h. 포스트모템엔 없는 선택 근거.",
     ["정산 배치", "fail-closed 원칙"]),
    ("raw/slack/2026-05-16-keyboard-chat.md", "slack",
     "키보드 구매 잡담 — 업무 무관.",
     []),
    ("raw/slack/2026-05-19-pg-timeout-first-report.md", "slack",
     "PG 타임아웃 최초 보고 — 가맹점 CS('결제가 빙글빙글')로 인지, 토스 승인 하루 10~20건 타임아웃·PENDING 정체 확인. 토스 측 정상이라 자체 조사 착수(5/20 트러블슈팅으로 이어짐).",
     ["비동기 결제 승인", "PG 추상화"]),
    ("raw/slack/2026-05-21-bulkhead-deploy-result.md", "slack",
     "워커풀 분리(bulkhead) 배포 결과 — PG 타임아웃 0건. 웹훅 폭주가 결제 승인을 굶기던 구조의 해소 확인. 타임아웃 10s 단축+재시도 1회는 멱등키 덕에 안전.",
     ["비동기 결제 승인", "멱등성"]),
    ("raw/slack/2026-05-23-oncall-rotation.md", "slack",
     "**슬랙에서만 내려진 결정** — 온콜 주단위 3인 로테이션(서연·준호·민지) + 도현 상시 백업. PM은 1차 탐지/에스컬레이션 담당, 기술 대응은 백업 콜. 04시 배치 알람은 온콜 폰 라우팅.",
     ["온콜·알람"]),
    ("raw/slack/2026-05-26-newhire-news.md", "slack",
     "백엔드 신입 채용 확정(7월 입사) — 결정 히스토리가 문서 곳곳에 흩어져 있다는 문제의식과 함께 온보딩 가이드 작성 착수.",
     []),
    ("raw/slack/2026-05-28-batch-alert-tuning.md", "slack",
     "배치 알람 단계화 — INC-231 오판의 시작점이던 '30분 초과=알람'을 3단계로 분리: 60분 경고 / 송금 무응답 10분 긴급 / 락 있는데 프로세스 없음 긴급. 알람 문구에 '재실행 금지. 락 확인 먼저' 명시.",
     ["온콜·알람", "정산 배치"]),
    ("raw/slack/2026-06-02-refund-flow-open.md", "slack",
     "부분 환불 요구 증가 — 현재 전액 환불만 지원. 기정산 거래의 차감 정산·환불 멱등성 등 설계 이슈로 다음 분기 착수 결정(미결).",
     ["환불 플로우"]),
    ("raw/slack/2026-06-04-pg-minor-upgrade.md", "slack",
     "postgres 마이너 보안패치 공지 — 토요일 02시, 페일오버 1회 예상 10초 미만, in-flight 쿼리는 재시도로 흡수.",
     ["PostgreSQL 선택"]),
    ("raw/slack/2026-06-05-junho-handover.md", "slack",
     "준호 휴가 인수인계 — 시크릿 회전 API(PR-159) 리뷰 대기, 정산 CSV는 스펙 수령 후 복귀 시 착수, 온콜 교대 명시.",
     []),
    ("raw/slack/2026-06-09-settlement-csv-request.md", "slack",
     "가맹점 C 정산명세서 CSV 요구(거래ID/승인일시/금액/수수료/정산액) — C 전용이 아닌 대시보드 공통 기능으로 확장 결정, 이번달 내 제공 안내.",
     ["정산 배치"]),
    ("raw/slack/2026-06-10-idem-ttl-48h-proposal.md", "slack",
     "TTL 24h 만료 후 재시도 실측 7건(가맹점 배치 재처리 패턴) — 3/13에 보류한 엣지가 실재함을 확인. DB 유니크가 막아 사고는 아니나 캐시 미스로 409 혼란 발생, TTL 48h 제안. redis 메모리 추산 후 결정 예정(검토중).",
     ["멱등성"]),
    ("raw/slack/2026-06-11-onboarding-checklist.md", "slack",
     "신입 온보딩 체크리스트 — 멱등성 히스토리 세션은 도현 직접 진행('사고 친 사람이 설명'), 첫 과제는 정산 CSV 코드리뷰 참관으로 확정.",
     []),

    # ---------- pr (20) ----------
    ("raw/pr/pr-101-payment-gateway-interface.md", "pr-review",
     "PaymentGateway 인터페이스 PR — '어댑터는 동기, 비동기성은 워커 레벨'이라는 경계 확정. 부분취소는 시그니처 변경 없이 옵션 구조체로 확장 가능하게 유보.",
     ["PG 추상화", "비동기 결제 승인"]),
    ("raw/pr/pr-108-toss-adapter.md", "pr-review",
     "토스 어댑터 PR — 매핑 안 된 에러는 보수적으로 비재시도 분류(무한 재시도 방지), 에러 매핑 테이블을 상수 파일로 분리해 어댑터 간 공유.",
     ["PG 추상화"]),
    ("raw/pr/pr-112-idempotency-middleware.md", "pr-review",
     "**INC-204의 기원이 된 PR** — redis 타임아웃 처리를 두고 서연이 고민을 표했으나 도현이 '결제 못 받는 손실이 더 크다'며 fail-open(통과)을 결정. 준호의 중복 결제 우려에 'redis 가용성 높으니 일단'으로 머지. 한 달 뒤 INC-204로 이 판단이 뒤집힘.",
     ["멱등성", "fail-closed 원칙"]),
    ("raw/pr/pr-115-nice-adapter.md", "pr-review",
     "나이스 어댑터 PR — EUC-KR 응답 변환 처리, PR-108에서 정한 에러 매핑·비재시도 규칙 공유 확인.",
     ["PG 추상화"]),
    ("raw/pr/pr-118-webhook-sender-backoff.md", "pr-review",
     "웹훅 전송기 PR — 백오프에 ±20% jitter 추가(thundering herd 방지), 'at-least-once + 수신측 event_id 멱등'을 공식 전달 모델로 명문화.",
     ["웹훅 전송"]),
    ("raw/pr/pr-121-dead-letter-table.md", "pr-review",
     "dead letter 테이블 PR — 90일 보관 후 아카이브는 백로그로. 이메일 알림은 best-effort('기록은 보장, 알림은 노력').",
     ["웹훅 전송"]),
    ("raw/pr/pr-125-settlement-aggregation.md", "pr-review",
     "정산 집계 쿼리 PR — CTE 4단, 120만 건 4.2초 실측. 집계 경계는 `approved_at >= D AND < D+1` 반개구간으로 회의 결정('전일 00:00~23:59:59')을 중복/누락 없이 구현.",
     ["정산 배치", "PostgreSQL 선택"]),
    ("raw/pr/pr-127-fee-rounding.md", "pr-review",
     "수수료 계산 PR — 절사/반올림 정책 부재가 리뷰에서 발견됨. 약관 5조 2항('원 단위 미만 절사') 확인 후 절사로 확정, 조항 번호를 코드 주석에 기록.",
     ["수수료 계산", "정산 배치"]),
    ("raw/pr/pr-133-polling-worker.md", "pr-review",
     "PENDING 폴링 워커 PR — PG를 진실의 원천으로 삼아 10분 초과 PENDING을 재조회·동기화. 폴링 1분 주기, 토스 조회 rate limit(분당 600) 내 백프레셔.",
     ["비동기 결제 승인"]),
    ("raw/pr/pr-136-db-migration-numeric.md", "pr-review",
     "결제 테이블 마이그레이션 PR — NUMERIC(19,4) 채택 근거: 수수료 중간계산 손실 방지 + scale 변경 마이그레이션이 더 비쌈. over-engineering 이견 있었으나 수용.",
     ["PostgreSQL 선택"]),
    ("raw/pr/pr-140-hotfix-fail-closed.md", "pr-review",
     "INC-204 긴급 핫픽스 PR(당일 22:05 머지) — redis 타임아웃 시 503+Retry-After로 fail-closed 전환. 도현이 'PR-112에서 제가 fail-open으로 가자고 한 그 지점, 제 판단이 틀렸다'고 리뷰에 기록.",
     ["멱등성", "fail-closed 원칙"]),
    ("raw/pr/pr-142-payment-idempotency-unique.md", "pr-review",
     "DB 유니크 가드 구현 PR — ON CONFLICT DO NOTHING + RETURNING 관용구, 동시 도착 둘째 요청은 409 'processing'. 'redis=응답 재생 캐시, DB UNIQUE=멱등성의 진실' 계층 역할을 주석으로 명문화.",
     ["멱등성", "PostgreSQL 선택"]),
    ("raw/pr/pr-145-sdk-key-enforcement.md", "pr-review",
     "SDK 키 자동 생성 PR — '요청 객체 = 멱등성 단위'(같은 객체 재시도=같은 키, 새 객체=새 결제) 의미론 확정, 가맹점 혼동 1순위로 문서에 예제 명시.",
     ["멱등성"]),
    ("raw/pr/pr-148-hmac-signature.md", "pr-review",
     "HMAC 서명 PR — 재직렬화 json이 아닌 전송 버퍼 raw bytes로 서명(키 순서 버그 방지). timestamp 허용 오차 5분의 근거(시계 오차+재시도 지연, Stripe 동일) 기록. 회전 듀얼 키 검증은 PR-159로 분리.",
     ["웹훅 전송"]),
    ("raw/pr/pr-151-payout-unique-guard.md", "pr-review",
     "송금 유니크 가드 PR(INC-231 후속) — INSERT(initiated)가 송금 호출보다 먼저, 유니크 충돌 시 송금 자체를 스킵. initiated 고아 행은 1시간 후 수동 확인 큐로(자동 재송금은 위험해서 금지). '돈 나가는 건 모호하면 사람이 본다.'",
     ["정산 배치", "멱등성"]),
    ("raw/pr/pr-153-batch-distributed-lock.md", "pr-review",
     "배치 분산 락 PR — redis lock TTL 2h + 30분 heartbeat 연장(진짜 죽으면 자동 해제). 락 획득 실패 시 즉시 종료(fail-closed).",
     ["정산 배치", "fail-closed 원칙"]),
    ("raw/pr/pr-156-bulkhead-worker-pools.md", "pr-review",
     "워커풀 분리 PR — 결제 32(피크 TPS×PG 0.8s=26+여유)/웹훅 16 산정식 기록. 웹훅은 큐 대기+디스크 백업 큐로 유실 방지. '결제는 빠르게, 웹훅은 반드시.'",
     ["비동기 결제 승인"]),
    ("raw/pr/pr-159-secret-rotation-api.md", "pr-review",
     "시크릿 회전 API PR — **리뷰 보류 중**(작성자 휴가). 구 시크릿 유예 24h 하드코딩 vs 가맹점 선택 vs 72h 고정 사이에서 미결.",
     ["웹훅 전송"]),
    ("raw/pr/pr-162-settlement-csv-export.md", "pr-review",
     "정산 CSV 내보내기 — draft 상태. exporter 인터페이스로 PDF/CSV가 같은 데이터 소스 공유. BOM·스트리밍·다운로드 버튼 TODO.",
     ["정산 배치"]),
    ("raw/pr/pr-164-alert-tuning.md", "pr-review",
     "배치 알람 단계화 PR — 60분 경고 기준은 최근 60일 p99(52분) 실측 기반, 분기마다 재점검. '락 있는데 프로세스 없음'으로 죽음만 정밀 탐지. 알람 메시지에 '재실행 금지. 락 확인 먼저.'",
     ["온콜·알람", "정산 배치"]),

    # ---------- transcripts (8) ----------
    ("raw/transcripts/2026-03-04-kickoff-transcript.md", "transcript",
     "킥오프 STT 전문 — 정식 회의록엔 없는 배경 포함: 도현의 전 회사 PG 동기 연동 장애 트라우마가 비동기 결정의 동기. 토스 p99 3초 수치, 웹훅/폴링 병행 논리의 원맥락.",
     ["비동기 결제 승인", "PG 추상화", "멱등성"]),
    ("raw/transcripts/2026-03-25-settlement-transcript.md", "transcript",
     "정산 회의 STT 전문 — 실시간 정산 배제 논거(환불 정정 트랜잭션·건별 송금 수수료), 기준시각 경계 논의와 반개구간 구현 아이디어의 원맥락.",
     ["정산 배치", "멱등성"]),
    ("raw/transcripts/2026-04-08-db-choice-transcript.md", "transcript",
     "DB 회의 STT 전문 — mongo 논쟁 상세(개발 속도 vs 금액 필드 보호), postgres 우위 논거(FOR UPDATE·부분 인덱스·ON CONFLICT·윈도우 함수). BIGINT 이견은 '따로 하죠'로 미뤄짐(4/10 슬랙으로 이어짐).",
     ["PostgreSQL 선택"]),
    ("raw/transcripts/2026-04-23-inc204-postmortem-transcript.md", "transcript",
     "INC-204 포스트모템 STT — blameless 전제 하에 도현이 'fail-open은 PR-112에서 내가 밀었던 결정'임을 공식 인정. '결제 경로 외부 의존은 fail-closed 기본' 원칙과 DB 이중화 안이 여기서 확정. 회고문서의 원맥락.",
     ["멱등성", "fail-closed 원칙"]),
    ("raw/transcripts/2026-04-29-idempotency-v2-transcript.md", "transcript",
     "멱등성 2.0 결정 회의 STT — redis '진실→캐시' 역할 전환 명시, '3/11 결정을 수정하는 결정임을 회의록에 꼭 적어라(히스토리 연결)'는 도현 지시. 클라 생성 방식 자체는 옳았다는 평가.",
     ["멱등성", "fail-closed 원칙"]),
    ("raw/transcripts/2026-05-13-inc231-postmortem-transcript.md", "transcript",
     "INC-231 포스트모템 STT — 도현이 수동 재실행 본인임을 인정. 근본 원인 3개(송금 가드 부재·락 부재·죽음/지연 구분 정보 부재). 'INC-204와 같은 교훈인데 한 번에 일반화 못 했다'는 자책과 함께 '외부 부수효과 직전 유니크 가드, 모든 배치에 실행 락'을 원칙화.",
     ["정산 배치", "멱등성", "온콜·알람"]),
    ("raw/transcripts/2026-05-27-q2-retro-transcript.md", "transcript",
     "Q2 회고 STT — 잘한 것(당일 회수·구조적 재발방지) / 아쉬운 것(두 사고가 같은 교훈, 결정이 회의록·슬랙·PR에 흩어져 신입이 읽기 막막). 멱등성 히스토리를 '팀 사고방식의 압축판'으로 규정. 하반기 백로그(환불·라우팅·TTL 48h·dead letter 아카이브).",
     ["멱등성", "환불 플로우"]),
    ("raw/transcripts/2026-06-08-q3-planning-transcript.md", "transcript",
     "Q3 계획 STT — 환불 플로우를 메인으로(가맹점 요구 1순위, payout 가드와 같은 패턴 적용 가능), 멀티 PG 라우팅은 후반 설계 시작(토스 수수료 인상 대비, 어댑터 추상화 위에 라우팅 레이어). 신입 첫 과제는 CSV 참관 유지.",
     ["환불 플로우", "PG 추상화"]),

    # ---------- weekly (12) ----------
    ("raw/2026-03-06-weekly.md", "weekly",
     "주간 단신 — 킥오프 결정 공유, PG 인터페이스 PR 진행, 멱등성 조사 중, 가맹점 A·B 협의 시작.",
     ["PG 추상화", "멱등성"]),
    ("raw/2026-03-13-weekly.md", "weekly",
     "주간 단신 — 멱등성 결정 완료(클라 키+redis), TTL 24h 엣지 보류 기록, SDK 미사용 가맹점 공지 발송.",
     ["멱등성"]),
    ("raw/2026-03-20-weekly.md", "weekly",
     "주간 단신 — 웹훅 재시도 결정 완료, 어댑터 2종 진행(롤백 1회), 웹훅 전송기 구현 중.",
     ["웹훅 전송", "PG 추상화"]),
    ("raw/2026-03-27-weekly.md", "weekly",
     "주간 단신 — 정산 결정 완료 + 복합 유니크 키(슬랙 결정) 기록, 수수료 절사/반올림 정책 미확정이 PR-127 블로킹.",
     ["정산 배치", "수수료 계산"]),
    ("raw/2026-04-03-weekly.md", "weekly",
     "주간 단신 — 수수료 절사 확정(약관 5조 2항), 폴링 워커 머지, 데드락 해결, 가맹점 B 첫 결제.",
     ["수수료 계산", "비동기 결제 승인", "PostgreSQL 선택"]),
    ("raw/2026-04-10-weekly.md", "weekly",
     "주간 단신 — PostgreSQL+NUMERIC 결정·마이그레이션 머지, scale 4 채택, 프로모션 트래픽 3배 대비 시작.",
     ["PostgreSQL 선택"]),
    ("raw/2026-04-17-weekly.md", "weekly",
     "주간 단신 — 토스 rate limit 여유 확인, 웹훅 대시보드 베타, 프로모션 D-4 전원 대기 체제.",
     ["웹훅 전송", "비동기 결제 승인"]),
    ("raw/2026-04-24-weekly.md", "weekly",
     "주간 단신 — INC-204 수습 완료(87건 환불·포스트모템·fail-closed 핫픽스), DB 이중화 결정 회의 예정. 프로모션 자체 성공률 99.2%.",
     ["멱등성", "fail-closed 원칙"]),
    ("raw/2026-05-01-weekly.md", "weekly",
     "주간 단신 — 멱등성 2.0 결정 완료, 구현 PR 리뷰 중, HMAC 결정 회의 예정, 가맹점 C 연동 착수.",
     ["멱등성", "웹훅 전송"]),
    ("raw/2026-05-08-weekly.md", "weekly",
     "주간 단신 — HMAC 결정·구현 머지, 시크릿 pgcrypto 보관(슬랙 결정) 기록, 언어별 샘플 제공, 7/1 필수화 공지 준비.",
     ["웹훅 전송"]),
    ("raw/2026-05-15-weekly.md", "weekly",
     "주간 단신 — INC-231 수습 완료(1,840만원 당일 회수), payout 가드 머지·분산 락 리뷰 중·알람 단계화 착수.",
     ["정산 배치", "멱등성"]),
    ("raw/2026-05-22-weekly.md", "weekly",
     "주간 단신 — bulkhead 배포 후 PG 타임아웃 0건, 시크릿 회전 API 유예정책 미결, 온콜 로테이션 차주 시작, 신입 온보딩 준비 착수.",
     ["비동기 결제 승인", "웹훅 전송", "온콜·알람"]),
]

def git_hash(relpath):
    return subprocess.run(["git", "hash-object", relpath], cwd=ROOT,
                          capture_output=True, text=True, check=True).stdout.strip()

def main():
    n = 0
    for relpath, tag, summary, concepts in ENTRIES:
        h = git_hash(relpath)
        # 미러 경로: raw/slack/x.md → wiki/sources/slack/x.md, raw/x.md → wiki/sources/x.md
        sub = os.path.dirname(relpath)[len("raw"):].lstrip("/")
        out_dir = os.path.join(ROOT, "wiki", "sources", sub) if sub else os.path.join(ROOT, "wiki", "sources")
        os.makedirs(out_dir, exist_ok=True)
        concept_lines = "\n".join(f"- {c}" for c in concepts) if concepts else "- (없음 — 업무 무관/단순 공지)"
        body = f"""---
type: source
of: {relpath}
source_hash: {h}
tags: [source, {tag}]
---

## Summary
{summary}

## Concepts
{concept_lines}
"""
        with open(os.path.join(out_dir, os.path.basename(relpath)), "w", encoding="utf-8") as f:
            f.write(body)
        n += 1
    print(f"소스 요약 {n}개 생성 완료 → wiki/sources/ (미러 구조)")

if __name__ == "__main__":
    main()
